name: Delete Ephemeral Environment

on:
  delete:
    branches:
      - "feature/*"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Delete Ephemeral Stack
        run: |
          echo "Deleting ephemeral environment for branch: $GITHUB_REF"
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-')
          STACK_NAME="LambdaStack-${BRANCH_NAME}"

          echo "Deleting stack: $STACK_NAME"
          aws cloudformation delete-stack --stack-name "$STACK_NAME"
