name: Delete Ephemeral Environment on Merge

on:
  pull_request:
    branches:
      - main
    types: [closed] # triggers when the PR is closed or merged

jobs:
  cleanup:
    # Only proceed if the PR was actually merged (not just closed).
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Determine and Delete Ephemeral Stack
        run: |
          echo "Pull Request #${{ github.event.pull_request.number }} was merged into main."

          # $GITHUB_HEAD_REF is the branch name of the source (feature) branch in a pull request
          echo "Source branch: $GITHUB_HEAD_REF"

          # Convert any slashes (/) to dashes (-) so it matches the stack naming pattern
          BRANCH_NAME=$(echo "$GITHUB_HEAD_REF" | tr '/' '-')
          STACK_NAME="LambdaStack-${BRANCH_NAME}"

          echo "Deleting stack: $STACK_NAME"
          aws cloudformation delete-stack --stack-name "$STACK_NAME"
