name: Deploy Feature Stack with Terraform

on:
  push:
    branches:
      - "feature/*"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # 3. Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      # 4. Determine Branch Name
      #    We'll extract the feature branch and convert slashes to dashes (e.g., feature-test)
      - name: Determine Branch Name
        id: get_branch
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-')
          echo "branch_name=$BRANCH_NAME" >> "$GITHUB_OUTPUT"

      # 5. Build & Zip Your Lambda Functions
      - name: Build Lambda code
        run: |
          chmod +x ./bin/bash/build_functions.sh
          ./bin/bash/build_functions.sh

      # 6. Auto-generate .tf resources (Node.js script)
      - name: Generate Terraform config
        run: |
          cd scripts
          node auto_update_terraform.js

      # 7. Initialize Terraform
      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      # 8. Check & Import IAM + Lambda Resources (if they exist)
      - name: Check & Import Resources
        run: |
          cd terraform
          chmod +x ../bin/bash/check_import_resources.sh
          ../bin/bash/check_import_resources.sh ${{ steps.get_branch.outputs.branch_name }}

      # 9. Plan and Apply Terraform for the Feature Branch
      - name: Terraform Plan & Apply
        run: |
          cd terraform
          terraform plan -var="feature_name=${{ steps.get_branch.outputs.branch_name }}" -out=tfplan
          terraform apply -auto-approve tfplan
