name: Deploy Production Stack with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # 3. Install Python (it might already be on ubuntu-latest, but this ensures the correct version)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 4. Run your Python script to auto-generate .tf files
      #    Adjust paths as needed if your script is in a different folder
      - name: Generate Terraform config
        run: |
          cd terraform
          python auto_update_terraform.py
          ls -l

      # 5. Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      # 6. Terraform Init
      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      # 7. Terraform Plan & Apply
      - name: Terraform Plan & Apply
        run: |
          cd terraform
          terraform plan -var="feature_name=prod" -out=tfplan
          terraform apply -auto-approve tfplan
