name: Deploy Production Stack with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Configure AWS credentials using GitHub Secrets
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # 3. Install Terraform
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      # 4. (Optional) Build and Zip Your Lambda Functions
      #    If you have a script that zips each function into terraform/build/*.zip
      - name: Build Lambda code
        run: |
          chmod +x ./bin/bash/build_functions.sh
          ./bin/bash/build_functions.sh

      # 5. Initialize Terraform
      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      # 6. Plan and Apply Terraform for Production
      - name: Terraform Plan & Apply
        run: |
          cd terraform
          terraform plan -var="feature_name=prod" -out=tfplan
          terraform apply -auto-approve tfplan
